// src/components/Input.tsx
import  { useState } from 'react';
import { Eye, EyeOff } from 'lucide-react';
import type { FocusEvent, ReactNode } from 'react';

// Input Component
const Input = ({ 
  label,
  error,
  helper,
  type = 'text',
  size = 'md',
  variant = 'default',
  leftIcon,
  rightIcon,
  showPasswordToggle = false,
  fullWidth = true,
  placeholder,
  value,
  onChange,
  onFocus,
  onBlur,
  disabled = false,
  required = false,
  className = '',
  name
}:{
  label:string;
  error?:string;
  helper?:string;
  type?:string;
  size?:InputSize;
  variant?:InputVarient;
  leftIcon?:ReactNode;
  rightIcon?:ReactNode;
  showPasswordToggle?:boolean;
  fullWidth?:boolean;
  placeholder?:string;
  value?:string;
  onChange?:(value:string)=>void;
  onFocus?:any;
  onBlur?:any;
  disabled?:boolean;
  required?:boolean;
  className?:string;
  name?:string
}) => {
  
  const [showPassword, setShowPassword] = useState(false);
  const [focused, setFocused] = useState(false);
  
  const inputType = type === 'password' && showPassword ? 'text' : type;
  
  const baseClasses = `
    w-full transition-all duration-300 focus:outline-none 
    disabled:opacity-50 disabled:cursor-not-allowed
    placeholder:text-gray-400
  `;
  
  const variants = {
    default: `
      border-2 border-gray-300 focus:border-blue-600 focus:ring-4 focus:ring-blue-100
      bg-white hover:border-gray-400 disabled:bg-gray-50
    `,
    filled: `
      border-2 border-transparent bg-gray-100 focus:bg-white focus:border-blue-600 
      focus:ring-4 focus:ring-blue-100 hover:bg-gray-50 disabled:bg-gray-200
    `,
    underlined: `
      border-0 border-b-2 border-gray-300 focus:border-blue-600 bg-transparent
      rounded-none hover:border-gray-400 focus:ring-0
    `
  };
  
  const sizes = {
    sm: 'px-3 py-2 text-sm rounded-lg',
    md: 'px-4 py-3 text-base rounded-xl',
    lg: 'px-5 py-4 text-lg rounded-xl'
  };
  
  const inputClasses = `
    ${baseClasses}
    ${variants[variant]}
    ${sizes[size]}
    ${leftIcon ? (size === 'sm' ? 'pl-10' : size === 'lg' ? 'pl-14' : 'pl-12') : ''}
    ${rightIcon || (type === 'password' && showPasswordToggle) ? (size === 'sm' ? 'pr-10' : size === 'lg' ? 'pr-14' : 'pr-12') : ''}
    ${error ? 'border-red-500 focus:border-red-500 focus:ring-red-100' : ''}
    ${!fullWidth ? 'w-auto' : ''}
    ${variant === 'underlined' ? 'px-0' : ''}
    ${className}
  `;
  
  const labelClasses = `
    block text-sm font-medium mb-2 transition-colors duration-200
    ${error ? 'text-red-700' : focused ? 'text-blue-700' : 'text-gray-700'}
    ${required ? "after:content-['*'] after:ml-1 after:text-red-500" : ''}
  `;

  const handleFocus = (e:FocusEvent<HTMLInputElement,Element>) => {
    setFocused(true);
    if (onFocus) onFocus(e.target.value);
  };

  const handleBlur = (e:FocusEvent<HTMLInputElement,Element>) => {
    setFocused(false);
    if (onBlur) onBlur(e.target.value);
  };


  const inputName = label? label.replace(" ", "-").toLocaleLowerCase(): name;



  return (
    <div className={`${fullWidth ? 'w-full' : 'w-auto'}`}>
      {label && (
        <label className={labelClasses} id={inputName} htmlFor={inputName}>
          {label}
        </label>
      )}
      
      <div className="relative">
        {leftIcon && (
          <div className={`absolute top-1/2 -translate-y-1/2 left-3 text-gray-400 pointer-events-none`}>
            <span>
              {leftIcon}
            </span>
          </div>
        )}
        
        <input
          name={inputName}
          type={inputType}
          className={inputClasses}
          placeholder={placeholder}
          value={value}
          onChange={(e)=>onChange && onChange(e.target.value)}
          onFocus={handleFocus}
          onBlur={handleBlur}
          disabled={disabled}
          required={required}
        />
        
        {(rightIcon || (type === 'password' && showPasswordToggle)) && (
          <div className={`absolute top-1/2 -translate-y-1/2 right-3 flex items-center`}>
            {type === 'password' && showPasswordToggle ? (
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="text-gray-400 hover:text-gray-600 transition-colors duration-200 focus:outline-none focus:text-blue-600"
                disabled={disabled}
              >
                <span className='text-sm md:text-lg'>
                  {showPassword ? <EyeOff /> : <Eye />}
                </span>
              </button>
            ) : (
              <div className={`text-gray-400 pointer-events-none text-sm md:text-lg`}>
                {rightIcon}
              </div>
            )}
          </div>
        )}
      </div>
      
      {error && (
        <p className="mt-2 text-sm text-red-600 flex items-center">
          <svg className="w-4 h-4 mr-1 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
          {error}
        </p>
      )}
      
      {helper && !error && (
        <p className="mt-2 text-sm text-gray-500">{helper}</p>
      )}
    </div>
  );
};

export type InputType = 'text' | 'password' | 'email' | 'number';

export type InputVarient = 'filled' | 'underlined' | 'default';
export type InputSize = 'sm' | 'md' | 'lg';

export default Input;

// client/src/components/input/input.component.ts
import {
  Component,
  computed,
  input,
  InputSignal,
  output,
  OutputEmitterRef,
  Signal,
  signal,
  WritableSignal
} from '@angular/core';
import {Eye, EyeOff, LucideAngularModule, LucideIconData} from 'lucide-angular';
import {AbstractControl, FormControl, ReactiveFormsModule} from '@angular/forms';


@Component({
  selector: 'app-input',
  templateUrl: 'input.component.html',
  imports: [
    LucideAngularModule,
    ReactiveFormsModule
  ],
  standalone: true
})
export class Input{


  protected readonly EyeOff = EyeOff;
  protected readonly Eye = Eye;

  label:InputSignal<string|undefined> = input<string|undefined>(undefined);
  placeholder:InputSignal<string> = input<string>('');
  inputType:InputSignal<InputType> = input<InputType>('text');
  size:InputSignal<InputSize> = input<InputSize>('md');
  variant:InputSignal<InputVariant> = input<InputVariant>('default');
  focused:InputSignal<boolean> = input<boolean>(false);
  error:InputSignal<string|undefined>= input<string| undefined>(undefined);
  required:InputSignal<boolean> = input<boolean>(false);
  leftIcon:InputSignal<LucideIconData|undefined> = input<LucideIconData|undefined>(undefined);
  rightIcon:InputSignal<LucideIconData|undefined> = input<LucideIconData|undefined>(undefined);
  showPasswordToggle:InputSignal<boolean> = input<boolean>(false);
  fullWidth:InputSignal<boolean> = input<boolean>(false);
  classes:InputSignal<string> = input<string>('');
  name:InputSignal<string> = input<string>('');
  helper:InputSignal<string | undefined> = input<string|undefined>('');
  formControlVal:InputSignal<FormControl<any>> = input<FormControl<any>>(new FormControl());

  onFocus:OutputEmitterRef<string> = output<string>();
  onBlur:OutputEmitterRef<string> = output<string>();

  baseClasses:string = `
    w-full transition-all duration-300 focus:outline-none
    disabled:opacity-50 disabled:cursor-not-allowed
    placeholder:text-gray-400
  `;

  sizes = {
    sm: 'px-3 py-2 text-sm rounded-lg',
    md: 'px-4 py-3 text-base rounded-xl',
    lg: 'px-5 py-4 text-lg rounded-xl'
  };

  variants = {
    default: `
      border-2 border-gray-300 focus:border-blue-600 focus:ring-4 focus:ring-blue-100
      bg-white hover:border-gray-400 disabled:bg-gray-50
    `,
    filled: `
      border-2 border-transparent bg-gray-100 focus:bg-white focus:border-blue-600
      focus:ring-4 focus:ring-blue-100 hover:bg-gray-50 disabled:bg-gray-200
    `,
    underlined: `
      border-0 border-b-2 border-gray-300 focus:border-blue-600 bg-transparent
      rounded-none hover:border-gray-400 focus:ring-0
    `
  };

  labelClasses:Signal<string> = computed<string>(()=>{
    return `
    block text-sm font-medium mb-2 transition-colors duration-200
    ${this.error() ? 'text-red-700' : this.focused() ? 'text-blue-700' : 'text-gray-700'}
    ${this.required() ? "after:content-['*'] after:ml-1 after:text-red-500" : ''}
  `});

  inputClasses = computed(()=>{
    return `
    ${this.baseClasses}
    ${this.variants[this.variant()]}
    ${this.sizes[this.size()]}
    ${this.leftIcon() ? (this.size() === 'sm' ? 'pl-10' : this.size() === 'lg' ? 'pl-14' : 'pl-12') : ''}
    ${this.rightIcon() || (this.inputType() === 'password' && this.showPasswordToggle()) ? (this.size() === 'sm' ? 'pr-10' : this.size() === 'lg' ? 'pr-14' : 'pr-12') : ''}
    ${this.error() ? 'border-red-500 focus:border-red-500 focus:ring-red-100' : ''}
    ${!this.fullWidth() ? 'w-auto' : ''}
    ${this.variant() === 'underlined' ? 'px-0' : ''}
    ${this.classes()}
  `});

  isFocused:WritableSignal<boolean> = signal<boolean>(false);

  handleFocus = (e:FocusEvent) => {
    this.isFocused.set(true);
    this.onFocus.emit((e.target as HTMLInputElement).value);
  };

  handleBlur = (e:FocusEvent) => {
    this.isFocused.set(false);
    this.onBlur.emit((e.target as HTMLInputElement).value);
  };

  inputName = this.label() ? this.label()!.replace(" ", "-").toLocaleLowerCase(): this.name();

  showPassword:WritableSignal<boolean> = signal<boolean>(false);

  togglePasswordVisibility(){
    this.showPassword.update(pre=>!pre)
  }

  protected readonly type:Signal<InputType> = computed(()=>{
    if(this.inputType()=='password'){
        return this.showPassword()? 'text' : 'password';
    }
    return this.inputType();
  })




}


export type InputType = 'text' | 'password' | 'email' | 'number' | 'disabled';

export type InputVariant = 'filled' | 'underlined' | 'default';
export type InputSize = 'sm' | 'md' | 'lg';
