// src/pages/home/events/events.component.ts
import {Component} from '@angular/core';
import {Calendar, Clock, LucideAngularModule, MapPin} from 'lucide-angular';

@Component({
  selector: 'home-events',
  templateUrl: 'events.component.html',
  imports: [
    LucideAngularModule
  ],
  standalone: true
})
export class Events{

  events = [
    {
      title: "Tech Innovation Summit",
      date: "October 22, 2025",
      time: "9:00 AM - 5:00 PM",
      location: "Main Auditorium",
      category: "Conference",
    },
    {
      title: "Career Fair 2025",
      date: "November 5, 2025",
      time: "10:00 AM - 4:00 PM",
      location: "Sports Complex",
      category: "Career",
    },
    {
      title: "International Student Welcome",
      date: "September 25, 2025",
      time: "2:00 PM - 6:00 PM",
      location: "Student Center",
      category: "Social",
    },
  ];
  protected readonly Calendar = Calendar;
  protected readonly Clock = Clock;
  protected readonly MapPin = MapPin;
}

export type EventsType = {
  title: string,
  time: string,
  date: string,
  location: string,
  category: string,
}

<section class="py-20 bg-gray-50">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl lg:text-5xl font-bold text-primary mb-6">
        Upcoming Events
      </h2>
      <p class="text-xl text-gray-600">
        Join us for exciting events, seminars, and activities
      </p>
    </div>

    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
      @for (event of events; track event.title){
        <div
          class="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
        >
          <div class="flex items-center justify-between mb-4">
        <span
          class="px-3 py-1 rounded-full text-sm font-medium"
          [class]="event.category === 'Conference'
            ? 'bg-blue-100 text-blue-800'
            : event.category === 'Career'
            ? 'bg-green-100 text-green-800'
            : 'bg-purple-100 text-purple-800'"
      >
      {{ event.category }}
      </span>
            <lucide-angular [img]="Calendar" class="h-5 w-5 text-secondary"></lucide-angular>
    </div>
    <h3 class="text-xl font-bold text-primary mb-3">
      {{ event.title }}
    </h3>
    <div class="space-y-2 text-gray-600">
      <div class="flex items-center">
        <lucide-angular class="h-4 w-4 mr-2" [img]="Calendar"></lucide-angular>
        <span>{{ event.date }}</span>
      </div>
      <div class="flex items-center">
        <lucide-angular class="h-4 w-4 mr-2" [img]="Clock"></lucide-angular>
        <span>{{ event.time }}</span>
      </div>
      <div class="flex items-center">
        <lucide-angular [img]="MapPin" class="h-4 w-4 mr-2"></lucide-angular>
        <span>{{ event.location }}</span>
      </div>
    </div>
    <button class="mt-4 w-full bg-secondary hover:bg-primary text-white py-2 px-4 rounded-lg transition-colors duration-300">
      Learn More
    </button>
  </div>
      }

    </div>
  </div>
</section>

// src/components/Events.tsx
import { Calendar, Clock, MapPin } from "lucide-react";

const Events = () => {



  const events = [
    {
      title: "Tech Innovation Summit",
      date: "October 22, 2025",
      time: "9:00 AM - 5:00 PM",
      location: "Main Auditorium",
      category: "Conference",
    },
    {
      title: "Career Fair 2025",
      date: "November 5, 2025",
      time: "10:00 AM - 4:00 PM",
      location: "Sports Complex",
      category: "Career",
    },
    {
      title: "International Student Welcome",
      date: "September 25, 2025",
      time: "2:00 PM - 6:00 PM",
      location: "Student Center",
      category: "Social",
    },
  ];

  return (
    <section className="py-20 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl lg:text-5xl font-bold text-primary mb-6">
            Upcoming Events
          </h2>
          <p className="text-xl text-gray-600">
            Join us for exciting events, seminars, and activities
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {events.map((event, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
            >
              <div className="flex items-center justify-between mb-4">
                <span
                  className={`px-3 py-1 rounded-full text-sm font-medium ${
                    event.category === "Conference"
                      ? "bg-blue-100 text-blue-800"
                      : event.category === "Career"
                      ? "bg-green-100 text-green-800"
                      : "bg-purple-100 text-purple-800"
                  }`}
                >
                  {event.category}
                </span>
                <Calendar className="h-5 w-5 text-secondary" />
              </div>
              <h3 className="text-xl font-bold text-primary mb-3">
                {event.title}
              </h3>
              <div className="space-y-2 text-gray-600">
                <div className="flex items-center">
                  <Calendar className="h-4 w-4 mr-2" />
                  <span>{event.date}</span>
                </div>
                <div className="flex items-center">
                  <Clock className="h-4 w-4 mr-2" />
                  <span>{event.time}</span>
                </div>
                <div className="flex items-center">
                  <MapPin className="h-4 w-4 mr-2" />
                  <span>{event.location}</span>
                </div>
              </div>
              <button className="mt-4 w-full bg-secondary hover:bg-primary text-white py-2 px-4 rounded-lg transition-colors duration-300">
                Learn More
              </button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Events
